services:
  # Database MySQL cho Web Store
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webstore
    ports:
      - "3306:3306"

  # Database PostgreSQL cho Finance
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: finance
    ports:
      - "5432:5432"

  # Dịch vụ Report (Module 3)
  report_service:
    build: ./report_service
    ports:
      - "8001:8000"
    depends_on:
      - mysql-db
      - postgres

  # Dịch vụ Legacy Adapter
  legacy-adapter:
    build: ./legacy_adapter
    depends_on:
      - mysql-db