services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_store
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - noah-network

  legacy-adapter:
    build: ./legacy_adapter
    volumes:
      - ./data/input:/app/input
      - ./data/processed:/app/processed
    depends_on:
      - mysql-db
    networks:
      - noah-network

  # --- MODULE 4: KONG GATEWAY ---
  kong:
    image: kong:3.4
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - noah-network
    depends_on:
      - mysql-db

  # DỊCH VỤ GIẢ (MOCK SERVICES) - Đã sửa 'args' thành 'command'
  order-api:
    image: hashicorp/http-echo
    command: ["-text", '{"message": "Gateway connected to Order API!"}']
    networks:
      - noah-network

  report-service:
    image: hashicorp/http-echo
    command: ["-text", '{"message": "Gateway connected to Report Service!"}']
    networks:
      - noah-network

networks:
  noah-network:
    driver: bridge